### PR TITLE
check query helper

### PR DESCRIPTION
**Pull request by irritanterik**
Check if query contains elements, don't add a ? query is an empty object

### CODE REVIEW

**Comment by matjaz** [comment]
can you elaborate why this is necessary?

**Comment by irritanterik** [comment]
An empty object now results in a ? added to the url / path.
So I have to check this and create a separate call to http.get (without
query param) on all places where I want to http.get.

2016-03-09 19:53 GMT+01:00 Matjaž Lipuš <notifications@github.com>:

**Comment by matjaz** [comment]
OK. I agree you should't need to do that.
My question is what's the problem with extra `?` added?

**Comment by irritanterik** [comment]
Some APIs like Philips Hue are very strict.

http://192.168.0.19/api/34d4c664bb7fdcf6caf28c30581757/lights/3/?
results in "*Bad URL in request" 😑*

2016-03-09 19:58 GMT+01:00 Matjaž Lipuš <notifications@github.com>:

**Comment by matjaz** [comment]
fixed in 7e4b39540361b94fc9e2338d557b0f17f79a6bfe version 1.2.2. Thanks!

**Pull request closed without merging**
